### ISSUE TITLE
Exception from executeScript:Failed to execute transaction-level behaviour

### ISSUE THREAD

**Issue by sumitt** [FlexSolution/SocialLogin#1]
Hi FlexSolution,

I have tried the module and got errors mentioned in my attachments. 
Alfresco is community version 5.2, SDK 3.0
(While I couldn't understand the first point SDK 3.0 in readme file and skipped that. Applied repo and share amps, setup linked developer). Now clicking "Signin with Linked in" gives me HTTP 400 and attached errors
[linkedin-issues.txt](https://github.com/FlexSolution/SocialLogin/files/1564656/linkedin-issues.txt).

Thanks.

**Comment by FlexSolution** [comment]
Hi,

You use some additional extensions that throw this exception. There is some Alfresco Behavior that tries to send email to a new user, that is created by using LinkedIn, but something goes wrong. Take a look at this part of error log:

```
at com.eisenvault.repo.behaviour.GenerateNewUserWelcomeEmail.notifyUser(GenerateNewUserWelcomeEmail.java:69)
at com.eisenvault.repo.behaviour.GenerateNewUserWelcomeEmail.onCreateNode(GenerateNewUserWelcomeEmail.java:58)
```
