### ISSUE TITLE
When deploying in 201707 a blank form is shown for "OAuth2 Configuration" option

### ISSUE THREAD

**Issue by angelborroy-ks** [FlexSolution/SocialLogin#2]
Deployed on a clean 201707-GA out-of-the-box.

No changes made to authentication chain.

When I click "OAuth 2 Configuration" a blank page is shown. No JavaScript errors on the page. No Java errors on the server. 

Tested from Chrome and Firefox.

**Comment by FlexSolution** [comment]
Successfully tested on 201707 and on version 6 as well. Use `-force` parameter when apply amps
